### ISSUE TITLE
empty endpoint in DBSClient object returns HTML

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/dbs.js#26]
if I call the DBSClient object with an empty string or an wrong endpoint, it returns an HTML file instead of a error message.

Example:
const client = new DBSClient(''); 
 const storageInfo = await client.getStorageInfo();
console.log(storageInfo); // see response down bellow

Response:
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <title>@storybook/cli - Storybook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    
    <link rel="icon" type="image/svg+xml" href="./favicon.svg" />
    
    <link
      rel="prefetch"
      href="./sb-common-assets/nunito-sans-regular.woff2"
      as="font"
      type="font/woff2"
      crossorigin
    />
    <link
      rel="prefetch"
      href="./sb-common-assets/nunito-sans-bold.woff2"
      as="font"
      type="font/woff2"
      crossorigin
    />
    <link rel="stylesheet" href="./sb-common-assets/fonts.css" />

    <link href="./sb-manager/runtime.js" rel="modulepreload" />

    
    <link href="./sb-addons/essentials-controls-0/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-actions-1/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-backgrounds-2/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-viewport-3/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-toolbars-4/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-measure-5/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/essentials-outline-6/manager-bundle.js" rel="modulepreload" />
    
    <link href="./sb-addons/storybook-7/manager-bundle.js" rel="modulepreload" />
       

    <style>
      #storybook-root[hidden] {
        display: none !important;
      }
    </style>

    
  </head>
  <body>
    <div id="root"></div>

    
    <script>
      
        
          window['FEATURES'] = {
  "warnOnLegacyHierarchySeparator": true,
  "buildStoriesJson": false,
  "storyStoreV7": true,
  "argTypeTargetsV7": true,
  "legacyDecoratorFileOrder": false
};
        
      
        
          window['REFS'] = {};
        
      
        
          window['LOGLEVEL'] = "info";
        
      
        
          window['DOCS_OPTIONS'] = {
  "defaultName": "Docs",
  "autodocs": true
};
        
      
        
          window['CONFIG_TYPE'] = "DEVELOPMENT";
        
      
        
          window['VERSIONCHECK'] = "{\"success\":true,\"cached\":true,\"data\":{\"latest\":{\"version\":\"7.1.0\",\"info\":{\"plain\":\"Storybook 7.1 is here! 🎉\\n\\n- 🏄‍♀️ [**In-app onboarding**](https://storybook.js.org/blog/in-app-tour-for-new-users/) to help you set up new projects\\n- 💅 [**Zero-config styling support**](https://storybook.js.org/blog/zero-config-support-for-tailwind-mui-styled-components-and-emotion/) for major libraries\\n- 🗃️ [**API reference documentation**](https://storybook.js.org/blog/docs-updates/) and TypeScript-first snippets\\n- 📇 [**Table of Contents for docs**](https://storybook.js.org/docs/7.1/react/writing-docs/autodocs#generate-a-table-of-contents)\\n- 🎨 [**Figma** **Design addon**](https://github.com/storybookjs/addon-designs) official support\\n- 📗 **Vue3 source snippets** and reactivity improvements\\n- 💯 **Hundreds more** fixes and improvements\\n\\n7.1 contains hundreds more fixes, features, and tweaks. Browse the changelogs matching '7.1.0-alpha.*', '7.1.0-beta.*', and '7.1.0-rc.*' for the full list of changes.\\n\\nFor a better upgrade experience, please use one of the following commands:\\n\\nnpm or yarn 1:\\n'npx storybook@latest upgrade'\\n\\npnpm:\\n'pnpm dlx storybook@latest upgrade'\\n\\nyarn berry:\\n'yarn dlx storybook@latest upgrade'\"}},\"next\":{\"version\":\"7.1.0-rc.2\",\"info\":{\"plain\":\"- CLI: Exit when user does not select a storybook project type - [#23201](https://github.com/storybookjs/storybook/pull/23201), thanks [@yannbf](https://github.com/yannbf)!\\n- CLI: Fix Javascript language detection - [#23426](https://github.com/storybookjs/storybook/pull/23426), thanks [@valentinpalkovic](https://github.com/valentinpalkovic)!\\n- Core: Fix onboarding detection in what's new module - [#23424](https://github.com/storybookjs/storybook/pull/23424), thanks [@yannbf](https://github.com/yannbf)!\\n- Dependencies: Bump '@sveltejs/vite-plugin-svelte' - [#23233](https://github.com/storybookjs/storybook/pull/23233), thanks [@JReinhold](https://github.com/JReinhold)!\\n- Telemetry: Add globals usage to project.json - [#23431](https://github.com/storybookjs/storybook/pull/23431), thanks [@shilman](https://github.com/shilman)!\"}}},\"time\":1689770693980}";
        
      
        
      
    </script>
    

    <script type="module">
      import './sb-manager/runtime.js';

      
      import './sb-addons/essentials-controls-0/manager-bundle.js';
      
      import './sb-addons/essentials-actions-1/manager-bundle.js';
      
      import './sb-addons/essentials-backgrounds-2/manager-bundle.js';
      
      import './sb-addons/essentials-viewport-3/manager-bundle.js';
      
      import './sb-addons/essentials-toolbars-4/manager-bundle.js';
      
      import './sb-addons/essentials-measure-5/manager-bundle.js';
      
      import './sb-addons/essentials-outline-6/manager-bundle.js';
      
      import './sb-addons/storybook-7/manager-bundle.js';
      
    </script>

    <link href="./sb-preview/runtime.js" rel="prefetch" as="script" />
  </body>
</html>`

**Comment by jamiehewitt15** [comment]
ok yeah, the error handling can definitely be improved. This shouldn't take too long

**Comment by EnzoVezzaro** [comment]
well, something is off 😅

<img width="436" alt="Screenshot 2023-07-20 at 12 27 16" src="https://github.com/oceanprotocol/dbs.js/assets/13741335/510a634b-f132-4f79-9840-93a00b25700f">

**Comment by jamiehewitt15** [comment]
Yeah, localhost is filtered out, although you can use `http://127.0.0.1:8000` for testing. If that's a problem I can change it

**Comment by EnzoVezzaro** [comment]
maybe we should as the error message would be wrong in this case. It's not a big deal, but if you can just change it, this way we make it easier for a dev.

**Comment by jamiehewitt15** [comment]
This works now
